### ISSUE TITLE
y is empty or has only NAs

### ISSUE THREAD

**Issue by kylehamilton** [kylehamilton/MAJOR#20]
**Describe the bug**
Error reported by 艾文华 in meta-analysis of correlation coefficients. MAJOR reports that there is empty data or NAs where the data is entered correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/2274317/103386990-36deb380-4ab6-11eb-947e-64b5fd59f31a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Jamovi Version 1.6.8

**Data Set**
- Submitted over email

**Comment by kylehamilton** [comment]
Fixed bug, there was an error between variable names between SMD and COR that I didn't address at the time.

**Comment by onwayami2020** [comment]
Hi kylehamilton 

I got the same problem. Please how did you address the problem?

Thank you

**Comment by kylehamilton** [comment]
Check your data file and make sure that you don't have missing data or an extra row.

**Comment by onwayami2020** [comment]
Can I attached the data file. 

My data file has no missing value or extra raw.

**Comment by onwayami2020** [comment]
> Hi kylehamilton
> 
> I got the same problem. Please how did you address the problem?
> 
> Thank you

I even use one of the Example Dataset and it shows same problem

**Comment by onwayami2020** [comment]
![image](https://user-images.githubusercontent.com/72136175/105625680-be290800-5e65-11eb-8fbb-3b3b8ea44f4e.png)

**Comment by onwayami2020** [comment]
Hi

> Check your data file and make sure that you don't have missing data or an
extra row.

Hi,

I still got the same problem and I don't have missing data or extra raw.
Please advise.

Best regards,
Kabiru.
Personal Website <https://kmkura.com/>

Click this Link to Book an Appointment
<https://meet-with-kabiru-maitama-kura.appointlet.com/b/kabiru-maitama-kura>

**Comment by PabloInnk** [comment]
> I still got the same problem and I don't have missing data or extra raw. Please advise.

If you work with a recent version of Jamovi and module, try download older solid version of Jamovi (1.2.27) and install an older version of a module. I got the same problem as you and it helped me.

**Comment by onwayami2020** [comment]
Thanks, I'll take a look.

Best regards,
Kabiru.
Personal Website <https://kmkura.com/>

Click this Link to Book an Appointment
<https://meet-with-kabiru-maitama-kura.appointlet.com/b/kabiru-maitama-kura>

**Comment by Trebicky** [comment]
I am having the same problem in Effect size and sampling variance analysis. I have only two effects to analyse, no missing values no extra rows or columns.

Using MAJOR 1.2.1 on Jamovi 2.3.0.

Any news about a fix?
