### ISSUE TITLE
Confidence interval of meta effect size is different from JASP

### ISSUE THREAD

**Issue by RowlinAPsychologist** [kylehamilton/MAJOR#5]
z | SE(z)
-- | --
0.28 | 0.15
0.46 | 0.16
0.03 | 0.09
0.58 | 0.09
0.34 | 0.12
0.40 | 0.16
0.40 | 0.15
0.19 | 0.09
0.54 | 0.12
0.29 | 0.12
-0.11 | 0.14
0.01 | 0.12
0.43 | 0.13
0.29 | 0.14
-0.03 | 0.17
0.03 | 0.09
0.08 | 0.11

* jamovi version: 0.8.1.14
* OS name and version: win10
* Analysis: meta-analysis, overall effect size
* Steps to reproduce: ML method

JASP (version 0.8.5.1) interval: .14 to .34; jamovi interval: .08 to .41
Both intervals are 95% by default, right?
Is it because of some methodological contention on formula?

**Comment by kylehamilton** [comment]
Hey Rowlin thanks for posting this issue. MAJOR uses the sampling variances where JASP uses standard errors. MAJOR uses the R package metafor for all of the backend calculations, I think JASP does the same thing but I'm not 100% sure. When I ran the data though metafor with the SE(z) data the results came out the same as you reported so it looks like that's the error. I'll add the option to use sampling variance or standard errors in the next release of MAJOR. 

![image](https://user-images.githubusercontent.com/2274317/35463275-a9c3d838-02a4-11e8-862d-1f2616673810.png)

![image](https://user-images.githubusercontent.com/2274317/35463109-eb1f0876-02a3-11e8-8ed5-f603de13fe85.png)

![image](https://user-images.githubusercontent.com/2274317/35463113-f19778f0-02a3-11e8-8856-0d762b02730d.png)
