### ISSUE TITLE
can"t open MAJOR!!

### ISSUE THREAD

**Issue by MohBaz** [kylehamilton/MAJOR#8]
I have problem opening MAJOR from the website??!!. I have reinstalled everthing again but still facing same issue
any advice
thanks

**Comment by kylehamilton** [comment]
Hi @MohBaz, what OS are you using and what version of Jamovi are you running? Can you send me (or attach here) a copy of the data you are working with?

**Comment by MohBaz** [comment]
Hi Kyle,

Thank for the quick respond. I have sorted everthing.
I apperciate your concern.

Best regards.

**Comment by kylehamilton** [comment]
Glad everything worked out! I have a development version that includes a lot of new features that you're free to try out. 

If you have any feedback, ideas, improvements, or requests please let me know I'm planning to release ann updated version of MAJOR soon!

[Video of the development version ](https://www.youtube.com/watch?v=LAoRw44Jx5w)

[Download MAJOR Development Version](https://github.com/kylehamilton/MAJOR/blob/30f3926dcd7aa895de204b9a6b84e38ed9e0969e/MAJOR_1.0.2-win64-R3.4.1.jmo)
