### ISSUE TITLE
Unable to perform moderation analyses

### ISSUE THREAD

**Issue by smancuso** [kylehamilton/MAJOR#9]
When I try to run a Mean Differences moderation analysis with a continuous variable (`year`) I get the following error message:

> y is empty or only has NAs

If I use the Effect Sizes and Sample Variances option, I get a different error:

> 'x' and 'y' lengths differ

Nonetheless,  _MAJOR_ is showing the correct output, but it is greyed out. I have checked this meta-regression analysis in _R_ and they concur with _MAJOR_.

I've attached the _jamovi_ along with the data
[Introduction to Meta-Analysis with jamovi.zip] as a zip file.

[Introduction to Meta-Analysis with jamovi.zip](https://github.com/kylehamilton/MAJOR/files/4195612/Introduction.to.Meta-Analysis.with.jamovi.zip)

**Comment by kylehamilton** [comment]
Ok I've pushed a patch that should take care of that problem. What happened was I set up some new features into the software but didn't test them with mixed effects models. Things should work on the mean differences option now. Let me know if you run into more problems
